export const siteConfig = {
  clubName: "TSV Poggenhagen",
  teamName: "1. Herren",
  league: "Kreisliga",
  region: "Neustadt",
  instagramHandle: "tsv.poggenhagen",
  instagramUrl: "https://www.instagram.com/tsv.poggenhagen/",
  fussballWidgets: {
    fixtures: "",
    results: "",
    table: "",
    nextMatch: "",
  },
  tableMode: "iframe" as "json" | "iframe",
  tableIframeUrl: "",
  endpoints: {
    fixtures: "/api/fixtures",
    results: "/api/results",
    table: "/api/table",
    instagram: "/api/instagram",
  },
  venue: {
    name: "Sportplatz Poggenhagen",
    address: "Ilschenheide 4, 31535 Neustadt am Rübenberge",
    mapsUrl: "https://maps.app.goo.gl/sDquMmHoEzkxwv4W8?g_st=ic",
  },
  navItems: [
    { label: "Start", href: "#hero" },
    { label: "Nächstes Spiel", href: "#naechstes-spiel" },
    { label: "Kader", href: "#kader" },
    { label: "Trainerstab", href: "#trainerstab" },
    { label: "Spielplan", href: "#spielplan" },
    { label: "Ergebnisse", href: "#ergebnisse" },
    { label: "Tabelle", href: "#tabelle" },
    { label: "Instagram", href: "#instagram" },
  ],
};
